FROM node:20.19.0-alpine

# Install git to clone the repository
RUN apk add --no-cache git

ENV PORT 1337
ENV HOST 0.0.0.0

WORKDIR /usr/src/app

# Clone the repository
RUN git clone https://github.com/apiaddicts/apiportal-cms .

RUN git pull

# Install app dependencies
RUN npm install

# Install pg for database connection
RUN npm install pg --save

# Bundle app source (no need for COPY . . as we cloned)

RUN npm run build

EXPOSE 1337

CMD [ "npm", "run", "start" ]
