FROM node:22.14.0-alpine

# Install git to clone the repository
RUN apk add --no-cache git

WORKDIR /usr/src/app

# Clone the repository
RUN git clone https://github.com/apiaddicts/apiportal-front .

# Install dependencies
RUN npm install

# Build the app (though it's not strictly necessary for dev mode, it's in the original flow)
RUN npm run build

EXPOSE 3000

# Start the dev server and expose it to the host
CMD [ "npm", "run", "start", "--", "--host" ]
